variable "frontend_app_sg" {}
variable "app_sg" {}
variable "public_subnets" {}
variable "app_subnets" {}
variable "web_tg" {}
variable "web_tg_name" {}
variable "app_tg" {}
variable "instance_type" {}
variable "app_tg_name" {}